---
title: "In-class_Ex10: Investment Vis Dashboard"
date: 2025-06-28
date-modified: "last-modified"
format: dashboard
editor: visual
execute: 
  eval: true
  echo: false
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse, tidyquant,
               timetk, plotly, glue)
```

```{r}
SGStock <- read_csv("data/SGStock.csv")
```

```{r}
daily_prices <- SGStock %>%
  select(Symbol) %>%
  tq_get(get = "stock.prices",
         from = "2025-01-01",
         to = Sys.Date())

daily_prices <- daily_prices %>%
  left_join(SGStock)
```

# DBS

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=25%}

```{r}
chosen_symbol_1 = "D05.SI"

daily_summary_1 <- daily_prices %>%
  filter(Symbol == chosen_symbol_1 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_1$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_1$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_1$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_1$low)
```

## Row

```{r}
chosen_name_1 = "DBS Group"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```


# OCBC

## Row {height=25%}

```{r}
chosen_symbol_2 = "O39.SI"

daily_summary_2 <- daily_prices %>%
  filter(Symbol == chosen_symbol_2 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_2$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_2$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_2$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_2$low)
```

## Row

```{r}
chosen_name_1 = "OCBC Bank"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```

# UOB

## Row {height=25%}

```{r}
chosen_symbol_3 = "U11.SI"

daily_summary_3 <- daily_prices %>%
  filter(Symbol == chosen_symbol_3 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_3$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_3$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_3$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_3$low)
```

## Row

```{r}
chosen_name_1 = "UOB"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```

# SingTel

## Row {height=25%}

```{r}
chosen_symbol_4 = "Z74.SI"

daily_summary_4 <- daily_prices %>%
  filter(Symbol == chosen_symbol_4 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_4$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_4$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_4$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_4$low)
```

## Row

```{r}
chosen_name_1 = "Singtel"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```

# SIA

## Row {height=25%}

```{r}
chosen_symbol_5 = "C6L.SI"

daily_summary_5 <- daily_prices %>%
  filter(Symbol == chosen_symbol_5 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_5$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_5$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_5$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_5$low)
```

## Row

```{r}
chosen_name_1 = "Singapore Airlines"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```

# CapitalLand Mall Trust

## Row {height=25%}

```{r}
chosen_symbol_6 = "C38U.SI"

daily_summary_6 <- daily_prices %>%
  filter(Symbol == chosen_symbol_6 &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary_6$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary_6$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"

list(color = "primary",
     value = daily_summary_6$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"

list(color = "primary",
     value = daily_summary_6$low)
```

## Row

```{r}
chosen_name_1 = "CapitaLand Mall Trust"

# Preparing the data
df <- daily_prices %>%
  filter(Name == chosen_name_1)

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("{chosen_name_1} Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line chart and the control chart
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl, color = "red", linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl,
           hjust = 0, colour = "darkgreen", size = 3.5) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = dynamic_title,
       y = "Closing Price", x = "") +
  theme_classic()

ggplotly(p)
```